import assert from 'node:assert/strict';
import { access } from 'node:fs/promises';
import { products, categories, normalize, productLabel } from '../src/lib/catalog.ts';
import { validQuantity, sanitizeCart, cartTotals, whatsappLink } from '../src/lib/cart.ts';
assert.equal(products.length, 38);
assert.equal(new Set(products.map(p => p.id)).size, 38);
assert.equal(categories.length, 2);
assert.equal(products.filter(p => p.category === 'flor-e-borboleta').length, 15);
const toppers = products.filter(p => p.category === 'topos-de-bolo');
assert.equal(toppers.length, 23);
for (const p of products) {
  assert.equal('price' in p, false);
  assert.equal(p.minimum, 10);
  assert.equal(p.images.length, p.category === 'flor-e-borboleta' ? 2 : 1);
  for (const image of p.images) await access(`public${image}`);
}
for (const q of [10, 11, 12, 13]) assert.ok(validQuantity(q));
for (const q of [0, 9, 10.5, -1, NaN, Infinity]) assert.equal(validQuantity(q), false);
assert.deepEqual(sanitizeCart({ 'rosa-claro': 11, 'azul-claro': 9, nope: 20, [toppers[0].id]: 10 }), { 'rosa-claro': 11, [toppers[0].id]: 10 });
assert.deepEqual(cartTotals({ 'rosa-claro': 11, 'azul-claro': 12, [toppers[0].id]: 10 }), { units: 33 });
assert.equal(normalize('LILÁS'), 'lilas');
assert.equal(normalize('Parabéns'), 'parabens');
assert.equal(whatsappLink('', { 'rosa-claro': 10 }), null);
assert.equal(whatsappLink('invalid', { 'rosa-claro': 10 }), null);
assert.equal(whatsappLink('5500000000000', {}), null);
const url = new URL(whatsappLink('5500000000000', { 'rosa-claro': 11, 'azul-claro': 12, [toppers[0].id]: 10 })!);
assert.equal(url.hostname, 'wa.me');
assert.equal(url.pathname, '/5500000000000');
const message = url.searchParams.get('text')!;
assert.match(message, /Rosa-claro: 11 unidades/);
assert.match(message, /Azul-claro: 12 unidades/);
assert.ok(message.includes(`${productLabel(toppers[0])}: 10 unidades`));
assert.match(message, /Quantidade total: 33 unidades/);
assert.doesNotMatch(message, /R\$|Subtotal|\d+[,.]\d{2}/);
assert.match(message, /valores.*disponibilidade.*frete/);
console.log('PASS: 38 products / 53 photos, two categories, unique IDs, no price data, minimum quantities, mixed cart, storage sanitization, accent search and price-free WhatsApp message. No messages sent.');
